### ISSUE TITLE
Segmentation fault when running TestMediaPlayer

### ISSUE THREAD

**Issue by joerg-krause** [openhome/ohPipeline#5]
This is the log running with gdb

```
ohPipeline ) gdb --args ./build/TestMediaPlayer --room "Living room" --name "nzxt"
GNU gdb (GDB) 8.0
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./build/TestMediaPlayer...done.
(gdb) run
Starting program: /home/joerg/Development/git/ohPipeline/build/TestMediaPlayer --room Living\ room --name nzxt
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff7fb3700 (LWP 30715)]
[New Thread 0x7ffff7f32700 (LWP 30716)]
[New Thread 0x7ffff7eb1700 (LWP 30717)]
[New Thread 0x7ffff6d5f700 (LWP 30718)]
adapter list:
  0: 192.168.178.46
using subnet 192.168.178.0
[New Thread 0x7ffff6cde700 (LWP 30719)]
[New Thread 0x7ffff6c5d700 (LWP 30720)]
[New Thread 0x7ffff6bdc700 (LWP 30721)]
[New Thread 0x7ffff6b5b700 (LWP 30722)]
[New Thread 0x7ffff6ada700 (LWP 30723)]
[New Thread 0x7ffff6a59700 (LWP 30724)]
[New Thread 0x7ffff69d8700 (LWP 30725)]
[New Thread 0x7ffff6957700 (LWP 30726)]
[New Thread 0x7ffff68d6700 (LWP 30727)]
[New Thread 0x7ffff6855700 (LWP 30728)]
[New Thread 0x7ffff67d4700 (LWP 30729)]
[New Thread 0x7ffff6753700 (LWP 30730)]
UPnP DV server using port: 35231
Seeding random number generator with: 36325
UDN is TestMediaPlayer-260261100
Shell running on port 40307
[New Thread 0x7ffff66d2700 (LWP 30731)]
[New Thread 0x7ffff6651700 (LWP 30732)]
[New Thread 0x7ffff65d0700 (LWP 30733)]
Stopper changing state from Stopped to Running
  iRemainingRampSize=0, iCurrentRampValue=00004000
[New Thread 0x7ffff654f700 (LWP 30734)]
[New Thread 0x7ffff64ce700 (LWP 30735)]
[New Thread 0x7ffff644d700 (LWP 30736)]
SetBalance: 0
SetFade: 0
[New Thread 0x7ffff63cc700 (LWP 30737)]
SetVolume: 0
SetVolume: 46080
SetVolume: 46080
SetVolume: 46080
[New Thread 0x7ffff634b700 (LWP 30738)]
[New Thread 0x7ffff62ca700 (LWP 30739)]
[New Thread 0x7ffff6249700 (LWP 30740)]
[New Thread 0x7ffff61c8700 (LWP 30741)]
[New Thread 0x7ffff6147700 (LWP 30742)]
[New Thread 0x7ffff60c6700 (LWP 30743)]
[New Thread 0x7ffff6045700 (LWP 30744)]
[New Thread 0x7ffff5fc4700 (LWP 30745)]
[New Thread 0x7ffff5f43700 (LWP 30746)]
[New Thread 0x7ffff5ec2700 (LWP 30747)]
[New Thread 0x7ffff5e41700 (LWP 30748)]
[New Thread 0x7ffff5d73700 (LWP 30749)]
[New Thread 0x7ffff5cf2700 (LWP 30750)]
RaopDiscoveryServer::RaopDiscoveryServer using network adapter 192.168.178.46
[New Thread 0x7ffff5c71700 (LWP 30751)]
[New Thread 0x7ffff5bf0700 (LWP 30752)]
[New Thread 0x7ffff5b6f700 (LWP 30753)]
[New Thread 0x7ffff5aee700 (LWP 30754)]
RaopControlServer::Run caught ReaderError
[New Thread 0x7ffff5a6d700 (LWP 30755)]
[New Thread 0x7ffff59ec700 (LWP 30756)]
[New Thread 0x7ffff596b700 (LWP 30757)]
[New Thread 0x7ffff58ea700 (LWP 30758)]
[New Thread 0x7ffff5869700 (LWP 30759)]
[New Thread 0x7ffff57e8700 (LWP 30760)]
ConfigAppBase::ConfigAppBase iResourcePrefix: Softplayer
CodecThread - search for new stream
[New Thread 0x7ffff5767700 (LWP 30761)]
ConfigManager: [
ConfigNum:
    {Sender.Channel, 26094}
    {Sender.Preset, 0}
    {Volume.Balance, 0}
    {Volume.Fade, 0}
    {Volume.Limit, 85}
    {Volume.StartupValue, 45}
ConfigChoice:
    {Device.AutoPlay, 0}
    {Device.StartupMode, 0}
    {Sender.Enabled, 1}
    {Sender.Mode, 1}
    {Source.Net Aux.Visible, 0}
    {Source.Playlist.Visible, 1}
    {Source.Radio.Visible, 1}
    {Source.Scd.Visible, 0}
    {Source.Songcast.Visible, 1}
    {Source.UPnP AV.Visible, 0}
    {Volume.Enabled, 1}
    {Volume.StartupEnabled, 1}
    {calmradio.com.Enabled, 1}
ConfigText:
    {Product.Name, nzxt}
    {Product.Room, Living room}
    {Source.Net Aux.Name, Net Aux}
    {Source.Playlist.Name, Playlist}
    {Source.Radio.Name, Radio}
    {Source.Scd.Name, Scd}
    {Source.Songcast.Name, Songcast}
    {Source.StartupName, Last Used}
    {Source.UPnP AV.Name, UPnP AV}
    {calmradio.com.Password, }
    {calmradio.com.Username, }
]
PipelineManager::StopPrefetch(Playlist, 0)
Filler::Stop()
Filler::StopLocked iStopped=1
SetVolume: 46080
IdManager::InvalidatePending()
Skipper::RemoveAll() - flush until haltId 2
Skipper::TryRemoveCurrentStream(0), iState=1, iRunning=0
Flusher(Skipper) DiscardUntilHalt(2)
Stopper::Play(), iState=Running
Flusher(Skipper), completed (pulled Halt id 2)
Skipper - completed flush (pulled haltId 2)
Pipeline state change: buffering
Drainer enabled (MsgHalt)
Filler::PlayLater(Playlist, 0)
SetVolume: 0
FILLER: iActiveUriProvider->GetNext() returned trackId=0, status=1
Drainer enabled (MsgHalt)
IdManager::AddStream(0, 0, 0)
Gorger::SetGorging(0) from ModeIn.  unblockRight=0
VariableDelayLeft::ProcessMsg(MsgDelay(8467200): delay=0(0), prev=0(0), iStatus=Starting
Pipeline report property: MODE {mode=Playlist; supportsLatency=0; supportsNext=1; supportsPrev=1}
CodecThread: start recognition.  iTrackId=0, iStreamId=0
VariableDelayRight::ProcessMsg(MsgDelay(8467200): delay=8467200(150), downstream=0(0), prev=0(0), iStatus=Starting
VariableDelay(right), delay=150, adjustment=150
Pipeline report property: TRACK {uri=; mode=Playlist; trackId=0; startOfStream=1}
ContainerController::OkToPlay aStreamId: 0
IdManager::OkToPlay(0) returning Later
Stopper - OkToPlay returned Later.  trackId=0, streamId=0.
Stopper changing state from Running to Stopped
  iRemainingRampSize=0, iCurrentRampValue=00004000
PipelineManager::PrefetchObserver::CheckTrack expected 0, got 0
Drainer enabled (MsgHalt)
Pipeline state change: stopped
Stopper::Pull(), waiting, iState=Stopped
RamStore: [
   {Device.AutoPlay, 0/}
   {Device.StartupMode, 0/}
   {Last.Source, Playlist}
   {Product.Name, 1853519988/nzxt}
   {Product.Room, Living room}
   {Sender.Channel, 26094/}
   {Sender.Enabled, 1/}
   {Sender.Mode, 1/}
   {Sender.Preset, 0/}
   {Source.Net Aux.Name, Net Aux}
   {Source.Net Aux.Visible, 0/}
   {Source.Playlist.Name, Playlist}
   {Source.Playlist.Visible, 1/}
   {Source.Radio.Name, Radio}
   {Source.Radio.Visible, 1/}
   {Source.Scd.Name, Scd}
   {Source.Scd.Visible, 0/}
   {Source.Songcast.Name, Songcast}
   {Source.Songcast.Visible, 1/}
   {Source.StartupName, Last Used}
   {Source.UPnP AV.Name, UPnP AV}
   {Source.UPnP AV.Visible, 0/}
   {Volume.Balance, 0/}
   {Volume.Enabled, 1/}
   {Volume.Fade, 0/}
   {Volume.Limit, 85/}
   {Volume.StartupEnabled, 1/}
   {Volume.StartupValue, 45/}
   {calmradio.com.Enabled, 1/}
   {calmradio.com.Password, }
   {calmradio.com.Username, }
]

Full (software) media player
Intended to be controlled via a separate, standard CP (Kazoo etc.)
Press <q> followed by <enter> to quit:

IdManager: InvalidateAfter(0.  Pending items are:
PipelineManager::StopPrefetch(Playlist, 1)
Filler::Stop()
Filler::StopLocked iStopped=1
IdManager::InvalidatePending()
Skipper::RemoveAll() - flush until haltId 3
Skipper::TryRemoveCurrentStream(0), iState=1, iRunning=0
ContainerController::TryStop aStreamId: 0
CodecController::TryStop(0) returning 0.  iStreamId=0, iStreamStopped=1
Flusher(Skipper) DiscardUntilHalt(3)
Stopper::Play(), iState=Stopped
Stopper changing state from Stopped to Running
  iRemainingRampSize=0, iCurrentRampValue=00004000
Pipeline state change: buffering
Drainer enabled (MsgHalt)
Filler::PlayLater(Playlist, 1)
CodecThread: recognition complete
ContainerController::OkToPlay aStreamId: 0
IdManager::OkToPlay(0) returning No - no streams pending
ContainerController::TryStop aStreamId: 0
CodecThread - search for new stream
FILLER: iActiveUriProvider->GetNext() returned trackId=1, status=2
>ProtocolRaop::DoInterrupt
Gorger::SetGorging(0) from ModeIn.  unblockRight=0
RaopAudioServer::DoInterrupt()
RaopControlServer::DoInterrupt
<ProtocolRaop::DoInterrupt
Flusher(Skipper), completed (pulled Halt id 3)
Skipper - completed flush (pulled haltId 3)
Drainer enabled (MsgHalt)
> iUriStreamer->DoStream(1)
ProtocolHttp::Stream(http://192.168.178.1:49200/AUDIO/DLNA-1-0/Musik/MIA/Stille%20Post/01%20-%20Komm%20mein%20M%c3%a4dchen.mp3)
>ProtocolNetwork::Connect
VariableDelayLeft::ProcessMsg(MsgDelay(8467200): delay=0(0), prev=0(0), iStatus=Starting
ProtocolNetwork::Open
VariableDelayRight::ProcessMsg(MsgDelay(8467200): delay=8467200(150), downstream=0(0), prev=0(0), iStatus=Starting
VariableDelay(right), delay=150, adjustment=150
Pipeline report property: METATEXT {}
Pipeline report property: MODE {mode=Playlist; supportsLatency=0; supportsNext=1; supportsPrev=1}
Pipeline report property: TRACK {uri=http://192.168.178.1:49200/AUDIO/DLNA-1-0/Musik/MIA/Stille%20Post/01%20-%20Komm%20mein%20M%c3%a4dchen.mp3; mode=Playlist; trackId=1; startOfStream=1}
Pipeline report property: METATEXT {}
<Protocol::Connect
ProtocolHttp::WriteRequest send request
ProtocolHttp::WriteRequest read response
ProtocolHttp::WriteRequest response code 206
ProtocolHttp::DoStream 'Partial Content' seekable=1 (7398505 bytes)
ProtocolHttp::ProcessContent 7398505
ProtocolHttp::StartStream
IdManager::AddStream(1, 1, 0)
CodecThread: start recognition.  iTrackId=1, iStreamId=1
Id3v2::Recognise
Id3v2 header found: 171475 bytes
Id3v2 header found: 171475 bytes
CodecThread: recognition complete
Gorger::SetGorging(1) from Pull.  unblockRight=0
ContainerController::OkToPlay aStreamId: 1
> ProtocolHttp::OkToPlay(1)
IdManager::OkToPlay(1) returning Later
< ProtocolHttp::OkToPlay(1) == Later
Stopper - OkToPlay returned Later.  trackId=1, streamId=1.
Stopper changing state from Running to Stopped
  iRemainingRampSize=0, iCurrentRampValue=00004000
PipelineManager::PrefetchObserver::CheckTrack expected 1, got 1
Pipeline state change: stopped
Drainer enabled (MsgHalt)
Pipeline report property: FORMAT {bitRate=241857; bitDepth=24, sampleRate=44100, numChannels=2, codec=MP3; trackLength=324498000, lossless=0, channelConfig=2/0.0}
Pipeline report property: TIME {secs=0; duration=239}
Stopper::Pull(), waiting, iState=Stopped

Thread 20 "TestMediaPlayer" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff65d0700 (LWP 30733)]
OpenHome::Media::Codec::CodecMp3::Process (this=0x7ffff104f880) at ../OpenHome/Media/Codec/Mp3.cpp:878
878	    if (iHeader.SamplesTotal()) {
(gdb) bt
#0  OpenHome::Media::Codec::CodecMp3::Process (this=0x7ffff104f880) at ../OpenHome/Media/Codec/Mp3.cpp:878
#1  0x00000000004ca8c1 in OpenHome::Media::Codec::CodecController::CodecThread (this=0x7ffff0f89ed0) at ../OpenHome/Media/Codec/CodecController.cpp:369
#2  0x000000000053a2b1 in OpenHome::Thread::EntryPoint (aArg=0x7ffff0f8a790) at OpenHome/Thread.cpp:170
#3  0x0000000000540da7 in threadEntrypoint (aArg=0x7ffff0f8aa50) at Os/Posix/Os.c:548
#4  0x00007ffff710c297 in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007ffff6e4d1ef in clone () from /usr/lib/libc.so.6
```

**Comment by joerg-krause** [comment]
Closed because of inactivity.
